### PR TITLE
Adding rudimentary aliasing option for injection

### PR DESCRIPTION
**Pull request by jeremyf**
Considerations:

* What to do with duplicates?
* What to do if we resolve an alias and it results in a duplicate name?

### CODE REVIEW

**Comment by solnic** [comment]
I think we should use a mapping hash internally even if it's `{ foo: :foo }` and it we should validate its structure on initialize so that the thing raises early when there are dups.

**Comment by jeremyf** [comment]
@solnic So, if I'm understanding the code, would mean pushing the alias-ing into Dry::Container

**Comment by jeremyf** [comment]
Here was a straw dog proposal. https://github.com/jeremyf/dry-container/commit/e4ad42aea10dbc770cc6061cb67ca423cc7c5691

**Comment by timriley** [comment]
I've just merged #7, which I think should support everything you wanted to do here :)

**Pull request closed without merging**
