### PR TITLE
Fix multiple injection for Kwargs strategy

### PR DESCRIPTION
**Pull request by flash-gordon**
Hey, @timriley! 

There is a minor issue with multiple injection. I found this when I worked with inheritance and injection trying inject modules in both parent and child classes.

### CODE REVIEW

**Comment by flash-gordon** [comment]
Oops, this fix doesn't work actually, but I'll figure that out.

**Comment by timriley** [comment]
Ok, I'll leave it with you :)

I was going to say it looked odd to have an "if super params.empty?" inside an "if super params.any?" clause, because in that structure, the "if empty?" code would never get run...

**Comment by flash-gordon** [comment]
@timriley this was a silly mistake, I set incorrect dependency name. Please take a closer look, `super_method.parameters` is not equal to `super_params` so that inner statement is called actually.

**Comment by timriley** [comment]
Ah yes, all makes sense! I'll take care of this for you tomorrow 👍🏼

**Pull request merged**
