### PR TITLE
Fix Usage

### PR DESCRIPTION
**Pull request by schnittchen**

### CODE REVIEW

**Comment by schnittchen** [comment]
I would also suggest replacing

`my_container[:data_store][:users]`

with 

`my_container[:data_store].users`

Otherwise brackets are used both for fetching from container and inside the (invisible) domain, which is confusing.

**Comment by timriley** [comment]
Thanks for this! However, I think it's probably best we made this README consistent with other dry-rb projects and have it simply link to the documentation on dry-rb.org (which is much better). 

Would you be happy to do that?

Thanks!

**Comment by schnittchen** [comment]
amended

**Comment by timriley** [comment]
Thanks!

**Pull request merged**
