### PR TITLE
improved GitHub diff link against main instead of master

### PR DESCRIPTION
**Pull request by ncreuschling**

### CODE REVIEW

**Comment by flash-gordon** [comment]
@ncreuschling thanks, but these files are auto-generated. However, I can't find the template, @solnic do you happen to know where it resides?

**Comment by ncreuschling** [comment]
I see.

**Comment by cllns** [comment]
It looks like the template gem already has this change, maybe it needs to be synced again to take effect: https://github.com/dry-rb/template-gem/commit/cbcc104827b982227b78099c1026afe74bc3e1a9

**Comment by solnic** [comment]
Yes once it's synced again. it'll be updated to use main

**Comment by flash-gordon** [comment]
I tried that but it still points to master https://github.com/dry-rb/dry-auto_inject/blob/main/CHANGELOG.md

**Comment by ncreuschling** [comment]
Maybe the problem is here: https://github.com/dry-rb/dry-auto_inject/blob/96f44e985e4aee71d7133838810935ae84431c3b/.devtools/templates/changelog.erb#L35

**Comment by solnic** [comment]
@ncreuschling oops, good catch. I missed this template when doing master => main migration 😢

**Pull request closed without merging**
